### ISSUE TITLE
Connection to server is not closed

### ISSUE THREAD

**Issue by genben** [althonos/fs.smbfs#1]
It is necessary to add the following method to `class SMBFS`:

    def __del__(self):
        if self._smb:
            self._smb.close()

Otherwise, the connection to the server is left opened until the server itself closes it by idle timeout (by default it is 15 minutes on Windows).
The Windows File Server rejects new connections if there are many idle connections with the following error:

    smb.smb_structs.ProtocolError: Unknown status value (0xC00000D0) in SMB_COM_SESSION_SETUP_ANDX (with extended security)

**Comment by althonos** [comment]
Indeed, although `self._smb` should be closed in `SMBFS.close` and not in `SMBFS.__del__`. I'll release a patch soon.

**Comment by althonos** [comment]
Fixed in `v0.2.4`.

**Comment by genben** [comment]
Thank you for adding the close() method.

I think, we still need the `__del__()` method as:

    def __del__(self):
        self.close()

Otherwise, the client application has to call the `close()` method explicitly when it is done with file system object. In our application, SBMFS() object is destroyed automatically by garbage collector when nobody references it, but the socket connection is not garbage collected for some reason (probably, there are some cross-references between multiple objects). 

P.S. It is not always convenient to use the context manager for life cycle management.
