### ISSUE TITLE
Is comma actually an invalid SMB path character?

### ISSUE THREAD

**Issue by SamRWest** [althonos/fs.smbfs#32]
Hi,

I've posted the details in the PyFilesystem2 issue here:
https://github.com/PyFilesystem/pyfilesystem2/issues/494

But now realise that this is probably best asked in this project.

It boils down to the question: are commas _actually_ invalid SMB path characters?  They seem to work fine for me, yet are included in `fs.smbfs.SMBFS._meta['invalid_path_chars']`. 

Is this a bug?

Cheers,
Sam.

**Comment by althonos** [comment]
Hi @SamRWest 

Actually, I don't think it is. I'll make a patch release to fix that.

**Comment by althonos** [comment]
Fixed in `v1.0.3`.
