### ISSUE TITLE
fs.geturl() returns smb://username@host:None/path

### ISSUE THREAD

**Issue by Timtam** [althonos/fs.smbfs#35]
I'd expect geturl() on a filesystem object to return either protocol://username:password@host[:port]/path or protocol://username@host[:port]/path, but geturl() in this case returns smb://username@host:None/path if no port was given explicitly, which seems to be wrong IMO.

**Comment by althonos** [comment]
Good catch, thanks. I'll release a patch.

**Comment by althonos** [comment]
Should be fixed in `v1.0.4`.
