### ISSUE TITLE
Documentation for listing shared network printers.

### ISSUE THREAD

**Issue by jonfen** [althonos/fs.smbfs#5]
Listing the shared files is cut and dry, but how do you list the shared printer names of a given computer?

Also asked here:
https://github.com/PyFilesystem/pyfilesystem2/issues/358

**Comment by althonos** [comment]
See my answer in the other issue :wink: 

You probably want a low-level SAMBA/SMB library to do this. Please check [`pysmb`](https://pysmb.readthedocs.io/en/latest/).

**Comment by jonfen** [comment]
> See my answer in the other issue wink
> 
> You probably want a low-level SAMBA/SMB library to do this. Please check [`pysmb`](https://pysmb.readthedocs.io/en/latest/).

I have this working with pysmbc (https://github.com/hamano/pysmbc/pull/38) but I need an MIT license package, not GPL.

**Comment by althonos** [comment]
Well, `pysmb` is `zlib/png` license, which is (IANAL) more permissive than GPL.
