### ISSUE TITLE
smb port defaults to 139 in SMBFS constructor but defaults to 445 in opener

### ISSUE THREAD

**Issue by telamonian** [althonos/fs.smbfs#8]
It looks like in the opener, the smb port defaults to 445:

https://github.com/althonos/fs.smbfs/blob/f9baeb4f5967969895d4b8a173eccc843b534e79/fs/opener/smbfs.py#L42-L44

However, in the SMBFS constructor the smb port definitely defaults to 139:

https://github.com/althonos/fs.smbfs/blob/f9baeb4f5967969895d4b8a173eccc843b534e79/fs/smbfs/smbfs.py#L204-L205

I initially didn't notice this issue when I was only working with shares exposed on Linux docker images (similar to the test case for this repo). However, now that I've started also working with local file servers on Windows this discrepancy has caused me no end of trouble.

Going by the [pysmb docs](https://pysmb.readthedocs.io/en/latest/api/smb_SMBConnection.html#smb.SMBConnection.SMBConnection.__init__), it seems like the most appropriate fix would be to use [a default smb port of 139](https://pysmb.readthedocs.io/en/latest/api/smb_SMBConnection.html#smb.SMBConnection.SMBConnection.connect) everywhere.

Another option would be to simply delegate the choice of default port to pysmb

**Comment by althonos** [comment]
Thanks for you PR!
